name: Setup Node EC2

on:
  workflow_dispatch:

jobs:
  setup-node:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2.pem
          chmod 600 ~/.ssh/ec2.pem

      - name: Install Node.js and prepare app
        run: |
          ssh -o StrictHostKeyChecking=no \
            -i ~/.ssh/ec2.pem \
            "${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}" << EOF

            set -e

            echo "Updating system..."
            sudo dnf update -y

            echo "Installing curl..."
            sudo dnf install -y curl

            echo "Installing Node.js..."
            curl -fsSL https://rpm.nodesource.com/setup_22.x | sudo bash -
            sudo dnf install -y nodejs

            echo "Creating application directory..."
            sudo mkdir -p "${{ secrets.APP_DIR }}"
            sudo chown -R \$USER:\$USER "${{ secrets.APP_DIR }}"

            echo "Node:"
            node --version

            echo "NPM:"
            npm --version

            echo "Application directory:"
            ls -ld "${{ secrets.APP_DIR }}"

            echo "EC2-1 setup completed."

          EOF