name: Setup k6 EC2

on:
  workflow_dispatch:

jobs:
  setup-k6:
    runs-on: ubuntu-latest

    steps:
      - name: Setup k6
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.K6_EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            echo "=== Updating EC2 ==="
            sudo dnf update -y

            echo "=== Installing required packages ==="
            sudo dnf install -y git curl

            echo "=== Installing k6 ==="

            sudo dnf install -y https://dl.k6.io/rpm/repo.rpm
            sudo dnf install -y k6

            echo "=== Checking versions ==="
            k6 version
            git --version

            echo "=== k6 setup complete ==="