name: Setup Database EC2

on:
  workflow_dispatch:

jobs:
  setup-db:
    runs-on: ubuntu-latest

    steps:
      - name: Setup PostgreSQL
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.DB_EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            echo "=== Updating EC2 ==="
            sudo dnf update -y

            echo "=== Installing PostgreSQL ==="
            sudo dnf install -y postgresql15 postgresql15-server

            echo "=== Initializing PostgreSQL ==="

            if [ ! -f /var/lib/pgsql/data/PG_VERSION ]; then
              sudo postgresql-setup --initdb
            fi

            echo "=== Starting PostgreSQL ==="
            sudo systemctl enable postgresql
            sudo systemctl start postgresql

            echo "=== Setting PostgreSQL password ==="
            sudo -u postgres psql <<EOF
            ALTER USER postgres WITH PASSWORD '${{ secrets.DB_PASSWORD }}';
            EOF

            echo "=== Creating database ==="

            sudo -u postgres psql -tc \
              "SELECT 1 FROM pg_database WHERE datname = 'migration_lab'" \
              | grep -q 1 || \
              sudo -u postgres createdb migration_lab

            echo "=== Configuring PostgreSQL network access ==="

            sudo sed -i \
              "s/^#listen_addresses = 'localhost'/listen_addresses = '*'/" \
              /var/lib/pgsql/data/postgresql.conf

            sudo sed -i \
              "s/^listen_addresses = 'localhost'/listen_addresses = '*'/" \
              /var/lib/pgsql/data/postgresql.conf

            echo "=== Allowing App EC2 ==="

            if ! sudo grep -q "172.31.48.80/32" /var/lib/pgsql/data/pg_hba.conf; then
              echo "host    migration_lab    postgres    172.31.48.80/32    scram-sha-256" \
                | sudo tee -a /var/lib/pgsql/data/pg_hba.conf
            fi

            echo "=== Restarting PostgreSQL ==="
            sudo systemctl restart postgresql

            echo "=== PostgreSQL status ==="
            sudo systemctl status postgresql --no-pager

            echo "=== Database setup complete ==="